#Super SOM

##Purpose

The purpose of this analysis is to make a superSOM.  

```{r}
library(ggplot2)
library(reshape)
library(plyr)
library(kohonen)
```
##PCA
Upload that dataset:

```{r}
genes25 <- read.csv("../data/analysis4.top25.csv")
head(genes25)
genes25 <- genes25[,c(2:14)]
m.genes25 <- melt(genes25)
head(m.genes25)

names(m.genes25) <- c("gene", "sample", "mean")

#set genotype

m.genes25$genotype <- ifelse(grepl("wt", m.genes25$sample, ignore.case = T), "wt", 
         ifelse(grepl("tf2", m.genes25$sample, ignore.case = T), "tf2", "unknown"))

#set tissue

m.genes25$tissue <- ifelse(grepl("other", m.genes25$sample, ignore.case = T), "other", 
         ifelse(grepl("mbr", m.genes25$sample, ignore.case = T), "mbr", "unknown"))

#Set Region
m.genes25$region <- ifelse(grepl("a", m.genes25$sample, ignore.case = T), "A", 
         ifelse(grepl("c", m.genes25$sample, ignore.case = T), "C", "B"))

#Set type

m.genes25$type <- paste(m.genes25$region, m.genes25$tissue,  sep = "")
head(m.genes25)
m.genes25.sub <- m.genes25[,c(1,7,4,3)]
head(m.genes25.sub)

#Change from long to wide data format
m.genes25.long <- cast(m.genes25.sub, genotype + gene ~ type, value.var = mean, fun.aggregate = "mean")  
m.genes25.long <- as.data.frame(m.genes25.long) 

m.genes25.long <- m.genes25.long[-c(870,1173,1437,1565,2247,4523),] #removing rows that caused NAs, see below for testing that was done.

```

```{r}
wt <- subset(m.genes25.long, genotype == "wt")

tf2 <- subset(m.genes25.long, genotype == "tf2")


scale_data.wt <- as.matrix(t(scale(t(wt[c(3:8)]))))#transformation.
scale_data.tf2 <- as.matrix(t(scale(t(tf2[c(3:8)]))))#transformation.

scale_data <- rbind(scale_data.wt, scale_data.tf2)
```

Testing a problem with NAs I ran into that caused me to remove these before analysis, I rean with out removing them and ran into some problems when binding everything back together. 
```{r}
#scale_data <- as.dataframe(scale_data)
#colSums(is.na(scale_data)) #there are six NAs in each column, double check where they came from. 

#new_DF_na2 <- subset(scale_data, is.na(scale_data$Cmbr))
#new_DF_na1 <- m.genes25.long[c(870,1173,1437,1565,2247,4523),] #they came from these rows, must remove them in the begining. 
```

Continuing on with PCA
```{r}
pca <- prcomp(scale_data, scale=TRUE) 

summary(pca) 

pca.scores <- data.frame(pca$x)

data.val <- cbind(m.genes25.long, scale_data, pca.scores) 
```


##Visualizing the PCA

```{r}
p <- ggplot(data.val, aes(PC1, PC2)) 
p + geom_point(alpha = 0.5)
```


##SuperSOM

```{r}
new_DF_na1

set.seed(6)
names(data.val)

superSomData <- data.val[,c(1:8)]

tf2 <- subset(superSomData, genotype == "tf2", select = 1:8)
wt <- subset(superSomData, genotype == "wt", select = 1:8)

wtdiff <- setdiff(wt$gene, tf2$gene) #find which genes differ

#remove them in WT

for (GENE in wtdiff) {
  wt <- wt[-grep(GENE, wt$gene),]
}

tf2 <- tf2[,3:8]
wt <- wt[,3:8]

wt <- as.matrix(wt)
tf2 <- as.matrix(tf2)

sc.wt <- t(scale(t(wt)))
sc.tf2 <- t(scale(t(tf2)))

dim(sc.tf2)
dim(sc.wt)

all.data <- list(sc.wt,sc.tf2)

ssom <- supersom(all.data, somgrid(3, 2, "hexagonal"),weights=c(0.5,0.5)) 

summary(ssom)
par(mfrow = c(3, 2))
plot(ssom, type ="changes")
plot(ssom, type = "codes")
plot(ssom, type = "counts")
plot(ssom, type = "quality")

data.val <- cbind(data.val,ssom$unit.classif,ssom$distances)

head(data.val)

write.table(data.val, file="../data/ssom.data.analysis5c.txt")
```

###Visualization 

```{r}
plot.data <- read.table("../data/ssom.data.analysis5c.txt",header=TRUE)
names(plot.data)
dim(plot.data)

p <- ggplot(plot.data, aes(PC1, PC2, colour=factor(ssom.unit.classif))) 
p + geom_point() + theme_bw()
```